### ISSUE TITLE
✨ [FEAT] 스웨거 세팅

### ISSUE THREAD

**Issue by mmingoo** [Team-GAJI/GAJI-Server#10]
## 💡 구현할 기능 설명

Swagger 세팅을 위한 기능 추가입니다.

테스트를 진행하실 때 http://localhost:8080/swagger-ui/index.html 에 들어가셔서 API 테스트 하시면 됩니다.

**Comment by ShimFFF** [comment]
응답 통일 스웨거 세팅은 기능 개발에 가까워서 label feature로 바꿔주세요!

setting은 보통 DB 설정, 빌드, 테스트 도구 구축 등등에 씁니다!

**Comment by mmingoo** [comment]
알려주셔서 감사합니다!!
